-- Seed file for exercises table
-- Consolidated bulk INSERT from individual statements
-- Total exercises: 170

INSERT INTO exercises (
  name, slug, primary_muscle, secondary_muscles, equipment,
  movement_pattern, exercise_type, difficulty, is_unilateral,
  image_path, instructions
) VALUES
(
  'Arnold Press',
  'arnold-press',
  'shoulders',
  '{}',
  'bodyweight',
  'push',
  'strength',
  'intermediate',
  false,
  'arnold-press.png',
  'Perform the movement with controlled tempo and proper form.'
),
(
  'Back Extension',
  'back-extension',
  'full_body',
  '{}',
  'bodyweight',
  'other',
  'strength',
  'intermediate',
  false,
  'back-extension.png',
  'Perform the movement with controlled tempo and proper form.'
),
(
  'Back Extension (Machine)',
  'back-extension-machine',
  'full_body',
  '{}',
  'machine',
  'other',
  'strength',
  'intermediate',
  false,
  'back-extension-machine.png',
  'Perform the movement with controlled tempo and proper form.'
),
(
  'Back Squat',
  'back-squat',
  'quadriceps',
  '{}',
  'bodyweight',
  'squat',
  'strength',
  'intermediate',
  false,
  'back-squat.png',
  'Perform the movement with controlled tempo and proper form.'
),
(
  'Bench Dip',
  'bench-dip',
  'triceps',
  '{}',
  'bodyweight',
  'other',
  'strength',
  'intermediate',
  false,
  'bench-dip.png',
  'Perform the movement with controlled tempo and proper form.'
),
(
  'Bench Press (Barbell)',
  'bench-press-barbell',
  'shoulders',
  '{}',
  'barbell',
  'push',
  'strength',
  'intermediate',
  false,
  'bench-press-barbell.png',
  'Perform the movement with controlled tempo and proper form.'
),
(
  'Bench Press (Dumbbell)',
  'bench-press-dumbbell',
  'shoulders',
  '{}',
  'dumbbell',
  'push',
  'strength',
  'intermediate',
  false,
  'bench-press-dumbbell.png',
  'Perform the movement with controlled tempo and proper form.'
),
(
  'Bent Over Row (Barbell)',
  'bent-over-row-barbell',
  'back',
  '{}',
  'barbell',
  'pull',
  'strength',
  'intermediate',
  false,
  'bent-over-row-barbell.png',
  'Perform the movement with controlled tempo and proper form.'
),
(
  'Bent Over Row (Dumbbell)',
  'bent-over-row-dumbbell',
  'back',
  '{}',
  'dumbbell',
  'pull',
  'strength',
  'intermediate',
  false,
  'bent-over-row-dumbbell.png',
  'Perform the movement with controlled tempo and proper form.'
),
(
  'Bicep Curl (Barbell)',
  'bicep-curl-barbell',
  'biceps',
  '{}',
  'barbell',
  'isolation',
  'strength',
  'intermediate',
  false,
  'bicep-curl-barbell.png',
  'Perform the movement with controlled tempo and proper form.'
),
(
  'Bicep Curl (Cable)',
  'bicep-curl-cable',
  'biceps',
  '{}',
  'cable',
  'isolation',
  'strength',
  'intermediate',
  false,
  'bicep-curl-cable.png',
  'Perform the movement with controlled tempo and proper form.'
),
(
  'Bicep Curl (Dumbbell)',
  'bicep-curl-dumbbell',
  'biceps',
  '{}',
  'dumbbell',
  'isolation',
  'strength',
  'intermediate',
  false,
  'bicep-curl-dumbbell.png',
  'Perform the movement with controlled tempo and proper form.'
),
(
  'Bulgarian Split Squat',
  'bulgarian-split-squat',
  'quadriceps',
  '{}',
  'bodyweight',
  'squat',
  'strength',
  'intermediate',
  false,
  'bulgarian-split-squat.png',
  'Perform the movement with controlled tempo and proper form.'
),
(
  'Cable Crossover',
  'cable-crossover',
  'full_body',
  '{}',
  'bodyweight',
  'other',
  'strength',
  'intermediate',
  false,
  'cable-crossover.png',
  'Perform the movement with controlled tempo and proper form.'
),
(
  'Cable Curl',
  'cable-curl',
  'biceps',
  '{}',
  'bodyweight',
  'isolation',
  'strength',
  'intermediate',
  false,
  'cable-curl.png',
  'Perform the movement with controlled tempo and proper form.'
),
(
  'Cable Lateral Raise',
  'cable-lateral-raise',
  'back',
  '{}',
  'bodyweight',
  'other',
  'strength',
  'intermediate',
  false,
  'cable-lateral-raise.png',
  'Perform the movement with controlled tempo and proper form.'
),
(
  'Cable Row',
  'cable-row',
  'back',
  '{}',
  'bodyweight',
  'pull',
  'strength',
  'intermediate',
  false,
  'cable-row.png',
  'Perform the movement with controlled tempo and proper form.'
),
(
  'Chest Dip',
  'chest-dip',
  'triceps',
  '{}',
  'bodyweight',
  'other',
  'strength',
  'intermediate',
  false,
  'chest-dip.png',
  'Perform the movement with controlled tempo and proper form.'
),
(
  'Chest Fly (Dumbbell)',
  'chest-fly-dumbbell',
  'full_body',
  '{}',
  'dumbbell',
  'other',
  'strength',
  'intermediate',
  false,
  'chest-fly-dumbbell.png',
  'Perform the movement with controlled tempo and proper form.'
),
(
  'Chest Fly (Machine)',
  'chest-fly-machine',
  'full_body',
  '{}',
  'machine',
  'other',
  'strength',
  'intermediate',
  false,
  'chest-fly-machine.png',
  'Perform the movement with controlled tempo and proper form.'
),
(
  'Chin Up',
  'chin-up',
  'full_body',
  '{}',
  'bodyweight',
  'other',
  'strength',
  'intermediate',
  false,
  'chin-up.png',
  'Perform the movement with controlled tempo and proper form.'
),
(
  'Clean',
  'clean',
  'full_body',
  '{}',
  'bodyweight',
  'other',
  'strength',
  'intermediate',
  false,
  'clean.png',
  'Perform the movement with controlled tempo and proper form.'
),
(
  'Clean and Press',
  'clean-and-press',
  'shoulders',
  '{}',
  'bodyweight',
  'push',
  'strength',
  'intermediate',
  false,
  'clean-and-press.png',
  'Perform the movement with controlled tempo and proper form.'
),
(
  'Concentration Curl',
  'concentration-curl',
  'biceps',
  '{}',
  'bodyweight',
  'isolation',
  'strength',
  'intermediate',
  false,
  'concentration-curl.png',
  'Perform the movement with controlled tempo and proper form.'
),
(
  'Crunch',
  'crunch',
  'core',
  '{}',
  'bodyweight',
  'other',
  'strength',
  'intermediate',
  false,
  'crunch.png',
  'Perform the movement with controlled tempo and proper form.'
),
(
  'Deadlift (Barbell)',
  'deadlift-barbell',
  'hamstrings',
  '{}',
  'barbell',
  'hinge',
  'strength',
  'intermediate',
  false,
  'deadlift-barbell.png',
  'Perform the movement with controlled tempo and proper form.'
),
(
  'Deadlift (Dumbbell)',
  'deadlift-dumbbell',
  'hamstrings',
  '{}',
  'dumbbell',
  'hinge',
  'strength',
  'intermediate',
  false,
  'deadlift-dumbbell.png',
  'Perform the movement with controlled tempo and proper form.'
),
(
  'Decline Bench Press',
  'decline-bench-press',
  'shoulders',
  '{}',
  'bodyweight',
  'push',
  'strength',
  'intermediate',
  false,
  'decline-bench-press.png',
  'Perform the movement with controlled tempo and proper form.'
),
(
  'Decline Sit Up',
  'decline-sit-up',
  'core',
  '{}',
  'bodyweight',
  'other',
  'strength',
  'intermediate',
  false,
  'decline-sit-up.png',
  'Perform the movement with controlled tempo and proper form.'
),
(
  'Dumbbell Row',
  'dumbbell-row',
  'back',
  '{}',
  'bodyweight',
  'pull',
  'strength',
  'intermediate',
  false,
  'dumbbell-row.png',
  'Perform the movement with controlled tempo and proper form.'
),
(
  'EZ Bar Curl',
  'ez-bar-curl',
  'biceps',
  '{}',
  'bodyweight',
  'isolation',
  'strength',
  'intermediate',
  false,
  'ez-bar-curl.png',
  'Perform the movement with controlled tempo and proper form.'
),
(
  'Face Pull',
  'face-pull',
  'back',
  '{}',
  'bodyweight',
  'other',
  'strength',
  'intermediate',
  false,
  'face-pull.png',
  'Perform the movement with controlled tempo and proper form.'
),
(
  'Farmer Carry',
  'farmer-carry',
  'full_body',
  '{}',
  'bodyweight',
  'other',
  'strength',
  'intermediate',
  false,
  'farmer-carry.png',
  'Perform the movement with controlled tempo and proper form.'
),
(
  'Flat Bench Press',
  'flat-bench-press',
  'back',
  '{}',
  'bodyweight',
  'push',
  'strength',
  'intermediate',
  false,
  'flat-bench-press.png',
  'Perform the movement with controlled tempo and proper form.'
),
(
  'Front Raise',
  'front-raise',
  'shoulders',
  '{}',
  'bodyweight',
  'other',
  'strength',
  'intermediate',
  false,
  'front-raise.png',
  'Perform the movement with controlled tempo and proper form.'
),
(
  'Front Squat',
  'front-squat',
  'quadriceps',
  '{}',
  'bodyweight',
  'squat',
  'strength',
  'intermediate',
  false,
  'front-squat.png',
  'Perform the movement with controlled tempo and proper form.'
),
(
  'Glute Bridge',
  'glute-bridge',
  'full_body',
  '{}',
  'bodyweight',
  'other',
  'strength',
  'intermediate',
  false,
  'glute-bridge.png',
  'Perform the movement with controlled tempo and proper form.'
),
(
  'Glute Bridge (Barbell)',
  'glute-bridge-barbell',
  'full_body',
  '{}',
  'barbell',
  'other',
  'strength',
  'intermediate',
  false,
  'glute-bridge-barbell.png',
  'Perform the movement with controlled tempo and proper form.'
),
(
  'Goblet Squat',
  'goblet-squat',
  'quadriceps',
  '{}',
  'bodyweight',
  'squat',
  'strength',
  'intermediate',
  false,
  'goblet-squat.png',
  'Perform the movement with controlled tempo and proper form.'
),
(
  'Hack Squat',
  'hack-squat',
  'quadriceps',
  '{}',
  'bodyweight',
  'squat',
  'strength',
  'intermediate',
  false,
  'hack-squat.png',
  'Perform the movement with controlled tempo and proper form.'
),
(
  'Hammer Curl',
  'hammer-curl',
  'biceps',
  '{}',
  'bodyweight',
  'isolation',
  'strength',
  'intermediate',
  false,
  'hammer-curl.png',
  'Perform the movement with controlled tempo and proper form.'
),
(
  'Hang Clean',
  'hang-clean',
  'full_body',
  '{}',
  'bodyweight',
  'other',
  'strength',
  'intermediate',
  false,
  'hang-clean.png',
  'Perform the movement with controlled tempo and proper form.'
),
(
  'Hip Thrust',
  'hip-thrust',
  'full_body',
  '{}',
  'bodyweight',
  'other',
  'strength',
  'intermediate',
  false,
  'hip-thrust.png',
  'Perform the movement with controlled tempo and proper form.'
),
(
  'Hip Thrust (Barbell)',
  'hip-thrust-barbell',
  'full_body',
  '{}',
  'barbell',
  'other',
  'strength',
  'intermediate',
  false,
  'hip-thrust-barbell.png',
  'Perform the movement with controlled tempo and proper form.'
),
(
  'Incline Bench Press',
  'incline-bench-press',
  'shoulders',
  '{}',
  'bodyweight',
  'push',
  'strength',
  'intermediate',
  false,
  'incline-bench-press.png',
  'Perform the movement with controlled tempo and proper form.'
),
(
  'Incline Dumbbell Press',
  'incline-dumbbell-press',
  'shoulders',
  '{}',
  'bodyweight',
  'push',
  'strength',
  'intermediate',
  false,
  'incline-dumbbell-press.png',
  'Perform the movement with controlled tempo and proper form.'
),
(
  'Incline Curl',
  'incline-curl',
  'biceps',
  '{}',
  'bodyweight',
  'isolation',
  'strength',
  'intermediate',
  false,
  'incline-curl.png',
  'Perform the movement with controlled tempo and proper form.'
),
(
  'Jump Squat',
  'jump-squat',
  'quadriceps',
  '{}',
  'bodyweight',
  'squat',
  'strength',
  'intermediate',
  false,
  'jump-squat.png',
  'Perform the movement with controlled tempo and proper form.'
),
(
  'Kettlebell Swing',
  'kettlebell-swing',
  'full_body',
  '{}',
  'kettlebell',
  'other',
  'strength',
  'intermediate',
  false,
  'kettlebell-swing.png',
  'Perform the movement with controlled tempo and proper form.'
),
(
  'Lat Pulldown',
  'lat-pulldown',
  'back',
  '{}',
  'bodyweight',
  'other',
  'strength',
  'intermediate',
  false,
  'lat-pulldown.png',
  'Perform the movement with controlled tempo and proper form.'
),
(
  'Lat Pulldown (Wide Grip)',
  'lat-pulldown-wide-grip',
  'back',
  '{}',
  'wide grip',
  'other',
  'strength',
  'intermediate',
  false,
  'lat-pulldown-wide-grip.png',
  'Perform the movement with controlled tempo and proper form.'
),
(
  'Leg Curl',
  'leg-curl',
  'biceps',
  '{}',
  'bodyweight',
  'isolation',
  'strength',
  'intermediate',
  false,
  'leg-curl.png',
  'Perform the movement with controlled tempo and proper form.'
),
(
  'Leg Extension',
  'leg-extension',
  'full_body',
  '{}',
  'bodyweight',
  'other',
  'strength',
  'intermediate',
  false,
  'leg-extension.png',
  'Perform the movement with controlled tempo and proper form.'
),
(
  'Leg Press',
  'leg-press',
  'quadriceps',
  '{}',
  'bodyweight',
  'push',
  'strength',
  'intermediate',
  false,
  'leg-press.png',
  'Perform the movement with controlled tempo and proper form.'
),
(
  'Leg Raise',
  'leg-raise',
  'shoulders',
  '{}',
  'bodyweight',
  'other',
  'strength',
  'intermediate',
  false,
  'leg-raise.png',
  'Perform the movement with controlled tempo and proper form.'
),
(
  'Lunge',
  'lunge',
  'quadriceps',
  '{}',
  'bodyweight',
  'lunge',
  'strength',
  'intermediate',
  false,
  'lunge.png',
  'Perform the movement with controlled tempo and proper form.'
),
(
  'Military Press',
  'military-press',
  'shoulders',
  '{}',
  'bodyweight',
  'push',
  'strength',
  'intermediate',
  false,
  'military-press.png',
  'Perform the movement with controlled tempo and proper form.'
),
(
  'Mountain Climbers',
  'mountain-climbers',
  'full_body',
  '{}',
  'bodyweight',
  'other',
  'strength',
  'intermediate',
  false,
  'mountain-climbers.png',
  'Perform the movement with controlled tempo and proper form.'
),
(
  'Nordic Curl',
  'nordic-curl',
  'biceps',
  '{}',
  'bodyweight',
  'isolation',
  'strength',
  'intermediate',
  false,
  'nordic-curl.png',
  'Perform the movement with controlled tempo and proper form.'
),
(
  'Overhead Curl (Cable)',
  'overhead-curl-cable',
  'biceps',
  '{}',
  'cable',
  'isolation',
  'strength',
  'intermediate',
  false,
  'overhead-curl-cable.png',
  'Perform the movement with controlled tempo and proper form.'
),
(
  'Overhead Plate Raise',
  'overhead-plate-raise',
  'back',
  '{}',
  'bodyweight',
  'other',
  'strength',
  'intermediate',
  false,
  'overhead-plate-raise.png',
  'Perform the movement with controlled tempo and proper form.'
),
(
  'Overhead Press (Barbell)',
  'overhead-press-barbell',
  'shoulders',
  '{}',
  'barbell',
  'push',
  'strength',
  'intermediate',
  false,
  'overhead-press-barbell.png',
  'Perform the movement with controlled tempo and proper form.'
),
(
  'Overhead Press (Dumbbell)',
  'overhead-press-dumbbell',
  'shoulders',
  '{}',
  'dumbbell',
  'push',
  'strength',
  'intermediate',
  false,
  'overhead-press-dumbbell.png',
  'Perform the movement with controlled tempo and proper form.'
),
(
  'Overhead Squat',
  'overhead-squat',
  'quadriceps',
  '{}',
  'bodyweight',
  'squat',
  'strength',
  'intermediate',
  false,
  'overhead-squat.png',
  'Perform the movement with controlled tempo and proper form.'
),
(
  'Overhead Triceps Extension (Cable)',
  'overhead-triceps-extension-cable',
  'triceps',
  '{}',
  'cable',
  'other',
  'strength',
  'intermediate',
  false,
  'overhead-triceps-extension-cable.png',
  'Perform the movement with controlled tempo and proper form.'
),
(
  'Pendlay Row',
  'pendlay-row',
  'back',
  '{}',
  'bodyweight',
  'pull',
  'strength',
  'intermediate',
  false,
  'pendlay-row.png',
  'Perform the movement with controlled tempo and proper form.'
),
(
  'Pendulum Squat',
  'pendulum-squat',
  'quadriceps',
  '{}',
  'bodyweight',
  'squat',
  'strength',
  'intermediate',
  false,
  'pendulum-squat.png',
  'Perform the movement with controlled tempo and proper form.'
),
(
  'Pike Pushup',
  'pike-pushup',
  'full_body',
  '{}',
  'bodyweight',
  'other',
  'strength',
  'intermediate',
  false,
  'pike-pushup.png',
  'Perform the movement with controlled tempo and proper form.'
),
(
  'Pinwheel Curl (Dumbbell)',
  'pinwheel-curl-dumbbell',
  'biceps',
  '{}',
  'dumbbell',
  'isolation',
  'strength',
  'intermediate',
  false,
  'pinwheel-curl-dumbbell.png',
  'Perform the movement with controlled tempo and proper form.'
),
(
  'Pistol Squat',
  'pistol-squat',
  'quadriceps',
  '{}',
  'bodyweight',
  'squat',
  'strength',
  'intermediate',
  false,
  'pistol-squat.png',
  'Perform the movement with controlled tempo and proper form.'
),
(
  'Plank Pushup',
  'plank-pushup',
  'full_body',
  '{}',
  'bodyweight',
  'other',
  'strength',
  'intermediate',
  false,
  'plank-pushup.png',
  'Perform the movement with controlled tempo and proper form.'
),
(
  'Plate Curl',
  'plate-curl',
  'biceps',
  '{}',
  'bodyweight',
  'isolation',
  'strength',
  'intermediate',
  false,
  'plate-curl.png',
  'Perform the movement with controlled tempo and proper form.'
),
(
  'Plate Front Raise',
  'plate-front-raise',
  'back',
  '{}',
  'bodyweight',
  'other',
  'strength',
  'intermediate',
  false,
  'plate-front-raise.png',
  'Perform the movement with controlled tempo and proper form.'
),
(
  'Plate Press',
  'plate-press',
  'back',
  '{}',
  'bodyweight',
  'push',
  'strength',
  'intermediate',
  false,
  'plate-press.png',
  'Perform the movement with controlled tempo and proper form.'
),
(
  'Plate Squeeze (Svend Press)',
  'plate-squeeze-svend-press',
  'back',
  '{}',
  'svend press',
  'push',
  'strength',
  'intermediate',
  false,
  'plate-squeeze-svend-press.png',
  'Perform the movement with controlled tempo and proper form.'
),
(
  'Power Clean',
  'power-clean',
  'full_body',
  '{}',
  'bodyweight',
  'other',
  'strength',
  'intermediate',
  false,
  'power-clean.png',
  'Perform the movement with controlled tempo and proper form.'
),
(
  'Power Snatch',
  'power-snatch',
  'full_body',
  '{}',
  'bodyweight',
  'other',
  'strength',
  'intermediate',
  false,
  'power-snatch.png',
  'Perform the movement with controlled tempo and proper form.'
),
(
  'Rack Pull',
  'rack-pull',
  'back',
  '{}',
  'bodyweight',
  'other',
  'strength',
  'intermediate',
  false,
  'rack-pull.png',
  'Perform the movement with controlled tempo and proper form.'
),
(
  'Rear Delt Reverse Fly (Cable)',
  'rear-delt-reverse-fly-cable',
  'full_body',
  '{}',
  'cable',
  'other',
  'strength',
  'intermediate',
  false,
  'rear-delt-reverse-fly-cable.png',
  'Perform the movement with controlled tempo and proper form.'
),
(
  'Rear Delt Reverse Fly (Dumbbell)',
  'rear-delt-reverse-fly-dumbbell',
  'full_body',
  '{}',
  'dumbbell',
  'other',
  'strength',
  'intermediate',
  false,
  'rear-delt-reverse-fly-dumbbell.png',
  'Perform the movement with controlled tempo and proper form.'
),
(
  'Rear Delt Reverse Fly (Machine)',
  'rear-delt-reverse-fly-machine',
  'full_body',
  '{}',
  'machine',
  'other',
  'strength',
  'intermediate',
  false,
  'rear-delt-reverse-fly-machine.png',
  'Perform the movement with controlled tempo and proper form.'
),
(
  'Renegade Row (Dumbbell)',
  'renegade-row-dumbbell',
  'back',
  '{}',
  'dumbbell',
  'pull',
  'strength',
  'intermediate',
  false,
  'renegade-row-dumbbell.png',
  'Perform the movement with controlled tempo and proper form.'
),
(
  'Reverse Fly (Cable)',
  'reverse-fly-cable',
  'full_body',
  '{}',
  'cable',
  'other',
  'strength',
  'intermediate',
  false,
  'reverse-fly-cable.png',
  'Perform the movement with controlled tempo and proper form.'
),
(
  'Reverse Grip Lat Pulldown',
  'reverse-grip-lat-pulldown',
  'back',
  '{}',
  'bodyweight',
  'other',
  'strength',
  'intermediate',
  false,
  'reverse-grip-lat-pulldown.png',
  'Perform the movement with controlled tempo and proper form.'
),
(
  'Reverse Hyperextension',
  'reverse-hyperextension',
  'full_body',
  '{}',
  'bodyweight',
  'other',
  'strength',
  'intermediate',
  false,
  'reverse-hyperextension.png',
  'Perform the movement with controlled tempo and proper form.'
),
(
  'Sissy Squat (Weighted)',
  'sissy-squat-weighted',
  'quadriceps',
  '{}',
  'weighted',
  'squat',
  'strength',
  'intermediate',
  false,
  'sissy-squat-weighted.png',
  'Perform the movement with controlled tempo and proper form.'
),
(
  'Sit Up',
  'sit-up',
  'core',
  '{}',
  'bodyweight',
  'other',
  'strength',
  'intermediate',
  false,
  'sit-up.png',
  'Perform the movement with controlled tempo and proper form.'
),
(
  'Sit Up (Weighted)',
  'sit-up-weighted',
  'core',
  '{}',
  'weighted',
  'other',
  'strength',
  'intermediate',
  false,
  'sit-up-weighted.png',
  'Perform the movement with controlled tempo and proper form.'
),
(
  'Skating',
  'skating',
  'full_body',
  '{}',
  'bodyweight',
  'other',
  'strength',
  'intermediate',
  false,
  'skating.png',
  'Perform the movement with controlled tempo and proper form.'
),
(
  'Skiing',
  'skiing',
  'full_body',
  '{}',
  'bodyweight',
  'other',
  'strength',
  'intermediate',
  false,
  'skiing.png',
  'Perform the movement with controlled tempo and proper form.'
),
(
  'Skullcrusher (Barbell)',
  'skullcrusher-barbell',
  'triceps',
  '{}',
  'barbell',
  'other',
  'strength',
  'intermediate',
  false,
  'skullcrusher-barbell.png',
  'Perform the movement with controlled tempo and proper form.'
),
(
  'Skullcrusher (Dumbbell)',
  'skullcrusher-dumbbell',
  'triceps',
  '{}',
  'dumbbell',
  'other',
  'strength',
  'intermediate',
  false,
  'skullcrusher-dumbbell.png',
  'Perform the movement with controlled tempo and proper form.'
),
(
  'Sled Push',
  'sled-push',
  'full_body',
  '{}',
  'bodyweight',
  'other',
  'strength',
  'intermediate',
  false,
  'sled-push.png',
  'Perform the movement with controlled tempo and proper form.'
),
(
  'Snatch',
  'snatch',
  'full_body',
  '{}',
  'bodyweight',
  'other',
  'strength',
  'intermediate',
  false,
  'snatch.png',
  'Perform the movement with controlled tempo and proper form.'
),
(
  'Snowboarding',
  'snowboarding',
  'full_body',
  '{}',
  'bodyweight',
  'other',
  'strength',
  'intermediate',
  false,
  'snowboarding.png',
  'Perform the movement with controlled tempo and proper form.'
),
(
  'Spider Curl (Barbell)',
  'spider-curl-barbell',
  'biceps',
  '{}',
  'barbell',
  'isolation',
  'strength',
  'intermediate',
  false,
  'spider-curl-barbell.png',
  'Perform the movement with controlled tempo and proper form.'
),
(
  'Spider Curl (Dumbbell)',
  'spider-curl-dumbbell',
  'biceps',
  '{}',
  'dumbbell',
  'isolation',
  'strength',
  'intermediate',
  false,
  'spider-curl-dumbbell.png',
  'Perform the movement with controlled tempo and proper form.'
),
(
  'Spiderman',
  'spiderman',
  'full_body',
  '{}',
  'bodyweight',
  'other',
  'strength',
  'intermediate',
  false,
  'spiderman.png',
  'Perform the movement with controlled tempo and proper form.'
),
(
  'Spinning',
  'spinning',
  'full_body',
  '{}',
  'bodyweight',
  'other',
  'strength',
  'intermediate',
  false,
  'spinning.png',
  'Perform the movement with controlled tempo and proper form.'
),
(
  'Split Jerk',
  'split-jerk',
  'full_body',
  '{}',
  'bodyweight',
  'other',
  'strength',
  'intermediate',
  false,
  'split-jerk.png',
  'Perform the movement with controlled tempo and proper form.'
),
(
  'Split Squat (Dumbbell)',
  'split-squat-dumbbell',
  'quadriceps',
  '{}',
  'dumbbell',
  'squat',
  'strength',
  'intermediate',
  false,
  'split-squat-dumbbell.png',
  'Perform the movement with controlled tempo and proper form.'
),
(
  'Sprints',
  'sprints',
  'full_body',
  '{}',
  'bodyweight',
  'other',
  'strength',
  'intermediate',
  false,
  'sprints.png',
  'Perform the movement with controlled tempo and proper form.'
),
(
  'Squat (Band)',
  'squat-band',
  'quadriceps',
  '{}',
  'band',
  'squat',
  'strength',
  'intermediate',
  false,
  'squat-band.png',
  'Perform the movement with controlled tempo and proper form.'
),
(
  'Squat (Barbell)',
  'squat-barbell',
  'quadriceps',
  '{}',
  'barbell',
  'squat',
  'strength',
  'intermediate',
  false,
  'squat-barbell.png',
  'Perform the movement with controlled tempo and proper form.'
),
(
  'Squat (Bodyweight)',
  'squat-bodyweight',
  'quadriceps',
  '{}',
  'bodyweight',
  'squat',
  'strength',
  'intermediate',
  false,
  'squat-bodyweight.png',
  'Perform the movement with controlled tempo and proper form.'
),
(
  'Squat (Dumbbell)',
  'squat-dumbbell',
  'quadriceps',
  '{}',
  'dumbbell',
  'squat',
  'strength',
  'intermediate',
  false,
  'squat-dumbbell.png',
  'Perform the movement with controlled tempo and proper form.'
),
(
  'Squat (Machine)',
  'squat-machine',
  'quadriceps',
  '{}',
  'machine',
  'squat',
  'strength',
  'intermediate',
  false,
  'squat-machine.png',
  'Perform the movement with controlled tempo and proper form.'
),
(
  'Squat (Smith Machine)',
  'squat-smith-machine',
  'quadriceps',
  '{}',
  'smith machine',
  'squat',
  'strength',
  'intermediate',
  false,
  'squat-smith-machine.png',
  'Perform the movement with controlled tempo and proper form.'
),
(
  'Squat (Suspension)',
  'squat-suspension',
  'quadriceps',
  '{}',
  'suspension',
  'squat',
  'strength',
  'intermediate',
  false,
  'squat-suspension.png',
  'Perform the movement with controlled tempo and proper form.'
),
(
  'Squat Row',
  'squat-row',
  'quadriceps',
  '{}',
  'bodyweight',
  'squat',
  'strength',
  'intermediate',
  false,
  'squat-row.png',
  'Perform the movement with controlled tempo and proper form.'
),
(
  'Stair Machine (Floors)',
  'stair-machine-floors',
  'full_body',
  '{}',
  'floors',
  'other',
  'strength',
  'intermediate',
  false,
  'stair-machine-floors.png',
  'Perform the movement with controlled tempo and proper form.'
),
(
  'Stair Machine (Steps)',
  'stair-machine-steps',
  'full_body',
  '{}',
  'steps',
  'other',
  'strength',
  'intermediate',
  false,
  'stair-machine-steps.png',
  'Perform the movement with controlled tempo and proper form.'
),
(
  'Standing Cable Glute Kickbacks',
  'standing-cable-glute-kickbacks',
  'full_body',
  '{}',
  'bodyweight',
  'other',
  'strength',
  'intermediate',
  false,
  'standing-cable-glute-kickbacks.png',
  'Perform the movement with controlled tempo and proper form.'
),
(
  'Standing Calf Raise',
  'standing-calf-raise',
  'calves',
  '{}',
  'bodyweight',
  'other',
  'strength',
  'intermediate',
  false,
  'standing-calf-raise.png',
  'Perform the movement with controlled tempo and proper form.'
),
(
  'Standing Calf Raise (Barbell)',
  'standing-calf-raise-barbell',
  'calves',
  '{}',
  'barbell',
  'other',
  'strength',
  'intermediate',
  false,
  'standing-calf-raise-barbell.png',
  'Perform the movement with controlled tempo and proper form.'
),
(
  'Standing Calf Raise (Dumbbell)',
  'standing-calf-raise-dumbbell',
  'calves',
  '{}',
  'dumbbell',
  'other',
  'strength',
  'intermediate',
  false,
  'standing-calf-raise-dumbbell.png',
  'Perform the movement with controlled tempo and proper form.'
),
(
  'Standing Calf Raise (Machine)',
  'standing-calf-raise-machine',
  'calves',
  '{}',
  'machine',
  'other',
  'strength',
  'intermediate',
  false,
  'standing-calf-raise-machine.png',
  'Perform the movement with controlled tempo and proper form.'
),
(
  'Standing Calf Raise (Smith)',
  'standing-calf-raise-smith',
  'calves',
  '{}',
  'smith',
  'other',
  'strength',
  'intermediate',
  false,
  'standing-calf-raise-smith.png',
  'Perform the movement with controlled tempo and proper form.'
),
(
  'Standing Leg Curls',
  'standing-leg-curls',
  'biceps',
  '{}',
  'bodyweight',
  'isolation',
  'strength',
  'intermediate',
  false,
  'standing-leg-curls.png',
  'Perform the movement with controlled tempo and proper form.'
),
(
  'Standing Military Press (Barbell)',
  'standing-military-press-barbell',
  'shoulders',
  '{}',
  'barbell',
  'push',
  'strength',
  'intermediate',
  false,
  'standing-military-press-barbell.png',
  'Perform the movement with controlled tempo and proper form.'
),
(
  'Step Up',
  'step-up',
  'quadriceps',
  '{}',
  'bodyweight',
  'other',
  'strength',
  'intermediate',
  false,
  'step-up.png',
  'Perform the movement with controlled tempo and proper form.'
),
(
  'Sternum Pull Up (Gironda)',
  'sternum-pull-up-gironda',
  'back',
  '{}',
  'gironda',
  'other',
  'strength',
  'intermediate',
  false,
  'sternum-pull-up-gironda.png',
  'Perform the movement with controlled tempo and proper form.'
),
(
  'Straight Arm Lat Pulldown (Cable)',
  'straight-arm-lat-pulldown-cable',
  'back',
  '{}',
  'cable',
  'other',
  'strength',
  'intermediate',
  false,
  'straight-arm-lat-pulldown-cable.png',
  'Perform the movement with controlled tempo and proper form.'
),
(
  'Straight Leg Deadlift',
  'straight-leg-deadlift',
  'hamstrings',
  '{}',
  'bodyweight',
  'hinge',
  'strength',
  'intermediate',
  false,
  'straight-leg-deadlift.png',
  'Perform the movement with controlled tempo and proper form.'
),
(
  'Stretching',
  'stretching',
  'full_body',
  '{}',
  'bodyweight',
  'other',
  'strength',
  'intermediate',
  false,
  'stretching.png',
  'Perform the movement with controlled tempo and proper form.'
),
(
  'Sumo Deadlift',
  'sumo-deadlift',
  'hamstrings',
  '{}',
  'bodyweight',
  'hinge',
  'strength',
  'intermediate',
  false,
  'sumo-deadlift.png',
  'Perform the movement with controlled tempo and proper form.'
),
(
  'Sumo Squat',
  'sumo-squat',
  'quadriceps',
  '{}',
  'bodyweight',
  'squat',
  'strength',
  'intermediate',
  false,
  'sumo-squat.png',
  'Perform the movement with controlled tempo and proper form.'
),
(
  'Sumo Squat (Barbell)',
  'sumo-squat-barbell',
  'quadriceps',
  '{}',
  'barbell',
  'squat',
  'strength',
  'intermediate',
  false,
  'sumo-squat-barbell.png',
  'Perform the movement with controlled tempo and proper form.'
),
(
  'Sumo Squat (Dumbbell)',
  'sumo-squat-dumbbell',
  'quadriceps',
  '{}',
  'dumbbell',
  'squat',
  'strength',
  'intermediate',
  false,
  'sumo-squat-dumbbell.png',
  'Perform the movement with controlled tempo and proper form.'
),
(
  'Sumo Squat (Kettlebell)',
  'sumo-squat-kettlebell',
  'quadriceps',
  '{}',
  'kettlebell',
  'squat',
  'strength',
  'intermediate',
  false,
  'sumo-squat-kettlebell.png',
  'Perform the movement with controlled tempo and proper form.'
),
(
  'Superman',
  'superman',
  'lower_back',
  '{}',
  'bodyweight',
  'other',
  'strength',
  'intermediate',
  false,
  'superman.png',
  'Perform the movement with controlled tempo and proper form.'
),
(
  'Swimming',
  'swimming',
  'full_body',
  '{}',
  'bodyweight',
  'other',
  'strength',
  'intermediate',
  false,
  'swimming.png',
  'Perform the movement with controlled tempo and proper form.'
),
(
  'T Bar Row',
  't-bar-row',
  'back',
  '{}',
  'bodyweight',
  'pull',
  'strength',
  'intermediate',
  false,
  't-bar-row.png',
  'Perform the movement with controlled tempo and proper form.'
),
(
  'Thruster (Barbell)',
  'thruster-barbell',
  'full_body',
  '{}',
  'barbell',
  'other',
  'strength',
  'intermediate',
  false,
  'thruster-barbell.png',
  'Perform the movement with controlled tempo and proper form.'
),
(
  'Thruster (Kettlebell)',
  'thruster-kettlebell',
  'full_body',
  '{}',
  'kettlebell',
  'other',
  'strength',
  'intermediate',
  false,
  'thruster-kettlebell.png',
  'Perform the movement with controlled tempo and proper form.'
),
(
  'Toe Touch',
  'toe-touch',
  'full_body',
  '{}',
  'bodyweight',
  'other',
  'strength',
  'intermediate',
  false,
  'toe-touch.png',
  'Perform the movement with controlled tempo and proper form.'
),
(
  'Toes to Bar',
  'toes-to-bar',
  'full_body',
  '{}',
  'bodyweight',
  'other',
  'strength',
  'intermediate',
  false,
  'toes-to-bar.png',
  'Perform the movement with controlled tempo and proper form.'
),
(
  'Torso Rotation',
  'torso-rotation',
  'full_body',
  '{}',
  'bodyweight',
  'other',
  'strength',
  'intermediate',
  false,
  'torso-rotation.png',
  'Perform the movement with controlled tempo and proper form.'
),
(
  'Treadmill',
  'treadmill',
  'full_body',
  '{}',
  'treadmill',
  'other',
  'strength',
  'intermediate',
  false,
  'treadmill.png',
  'Perform the movement with controlled tempo and proper form.'
),
(
  'Triceps Dip',
  'triceps-dip',
  'triceps',
  '{}',
  'bodyweight',
  'other',
  'strength',
  'intermediate',
  false,
  'triceps-dip.png',
  'Perform the movement with controlled tempo and proper form.'
),
(
  'Triceps Dip (Assisted)',
  'triceps-dip-assisted',
  'triceps',
  '{}',
  'assisted',
  'other',
  'strength',
  'intermediate',
  false,
  'triceps-dip-assisted.png',
  'Perform the movement with controlled tempo and proper form.'
),
(
  'Triceps Dip (Weighted)',
  'triceps-dip-weighted',
  'triceps',
  '{}',
  'weighted',
  'other',
  'strength',
  'intermediate',
  false,
  'triceps-dip-weighted.png',
  'Perform the movement with controlled tempo and proper form.'
),
(
  'Triceps Extension (Barbell)',
  'triceps-extension-barbell',
  'triceps',
  '{}',
  'barbell',
  'other',
  'strength',
  'intermediate',
  false,
  'triceps-extension-barbell.png',
  'Perform the movement with controlled tempo and proper form.'
),
(
  'Triceps Extension (Cable)',
  'triceps-extension-cable',
  'triceps',
  '{}',
  'cable',
  'other',
  'strength',
  'intermediate',
  false,
  'triceps-extension-cable.png',
  'Perform the movement with controlled tempo and proper form.'
),
(
  'Triceps Extension (Dumbbell)',
  'triceps-extension-dumbbell',
  'triceps',
  '{}',
  'dumbbell',
  'other',
  'strength',
  'intermediate',
  false,
  'triceps-extension-dumbbell.png',
  'Perform the movement with controlled tempo and proper form.'
),
(
  'Triceps Extension (Machine)',
  'triceps-extension-machine',
  'triceps',
  '{}',
  'machine',
  'other',
  'strength',
  'intermediate',
  false,
  'triceps-extension-machine.png',
  'Perform the movement with controlled tempo and proper form.'
),
(
  'Triceps Extension (Suspension)',
  'triceps-extension-suspension',
  'triceps',
  '{}',
  'suspension',
  'other',
  'strength',
  'intermediate',
  false,
  'triceps-extension-suspension.png',
  'Perform the movement with controlled tempo and proper form.'
),
(
  'Triceps Kickback (Cable)',
  'triceps-kickback-cable',
  'triceps',
  '{}',
  'cable',
  'other',
  'strength',
  'intermediate',
  false,
  'triceps-kickback-cable.png',
  'Perform the movement with controlled tempo and proper form.'
),
(
  'Triceps Kickback (Dumbbell)',
  'triceps-kickback-dumbbell',
  'triceps',
  '{}',
  'dumbbell',
  'other',
  'strength',
  'intermediate',
  false,
  'triceps-kickback-dumbbell.png',
  'Perform the movement with controlled tempo and proper form.'
),
(
  'Triceps Pressdown',
  'triceps-pressdown',
  'triceps',
  '{}',
  'bodyweight',
  'push',
  'strength',
  'intermediate',
  false,
  'triceps-pressdown.png',
  'Perform the movement with controlled tempo and proper form.'
),
(
  'Triceps Pushdown',
  'triceps-pushdown',
  'triceps',
  '{}',
  'bodyweight',
  'other',
  'strength',
  'intermediate',
  false,
  'triceps-pushdown.png',
  'Perform the movement with controlled tempo and proper form.'
),
(
  'Triceps Rope Pushdown',
  'triceps-rope-pushdown',
  'triceps',
  '{}',
  'bodyweight',
  'other',
  'strength',
  'intermediate',
  false,
  'triceps-rope-pushdown.png',
  'Perform the movement with controlled tempo and proper form.'
),
(
  'Upright Row (Barbell)',
  'upright-row-barbell',
  'back',
  '{}',
  'barbell',
  'pull',
  'strength',
  'intermediate',
  false,
  'upright-row-barbell.png',
  'Perform the movement with controlled tempo and proper form.'
),
(
  'Upright Row (Cable)',
  'upright-row-cable',
  'back',
  '{}',
  'cable',
  'pull',
  'strength',
  'intermediate',
  false,
  'upright-row-cable.png',
  'Perform the movement with controlled tempo and proper form.'
),
(
  'Upright Row (Dumbbell)',
  'upright-row-dumbbell',
  'back',
  '{}',
  'dumbbell',
  'pull',
  'strength',
  'intermediate',
  false,
  'upright-row-dumbbell.png',
  'Perform the movement with controlled tempo and proper form.'
),
(
  'V Up',
  'v-up',
  'core',
  '{}',
  'bodyweight',
  'other',
  'strength',
  'intermediate',
  false,
  'v-up.png',
  'Perform the movement with controlled tempo and proper form.'
),
(
  'Vertical Traction (Machine)',
  'vertical-traction-machine',
  'full_body',
  '{}',
  'machine',
  'other',
  'strength',
  'intermediate',
  false,
  'vertical-traction-machine.png',
  'Perform the movement with controlled tempo and proper form.'
),
(
  'Waiter Curl (Dumbbell)',
  'waiter-curl-dumbbell',
  'biceps',
  '{}',
  'dumbbell',
  'isolation',
  'strength',
  'intermediate',
  false,
  'waiter-curl-dumbbell.png',
  'Perform the movement with controlled tempo and proper form.'
),
(
  'Walking',
  'walking',
  'full_body',
  '{}',
  'bodyweight',
  'other',
  'strength',
  'intermediate',
  false,
  'walking.png',
  'Perform the movement with controlled tempo and proper form.'
),
(
  'Walking Lunge',
  'walking-lunge',
  'quadriceps',
  '{}',
  'bodyweight',
  'lunge',
  'strength',
  'intermediate',
  false,
  'walking-lunge.png',
  'Perform the movement with controlled tempo and proper form.'
),
(
  'Walking Lunge (Dumbbell)',
  'walking-lunge-dumbbell',
  'quadriceps',
  '{}',
  'dumbbell',
  'lunge',
  'strength',
  'intermediate',
  false,
  'walking-lunge-dumbbell.png',
  'Perform the movement with controlled tempo and proper form.'
),
(
  'Wall Ball',
  'wall-ball',
  'full_body',
  '{}',
  'bodyweight',
  'other',
  'strength',
  'intermediate',
  false,
  'wall-ball.png',
  'Perform the movement with controlled tempo and proper form.'
),
(
  'Wall Sit',
  'wall-sit',
  'full_body',
  '{}',
  'bodyweight',
  'other',
  'strength',
  'intermediate',
  false,
  'wall-sit.png',
  'Perform the movement with controlled tempo and proper form.'
),
(
  'Warm Up',
  'warm-up',
  'full_body',
  '{}',
  'bodyweight',
  'other',
  'strength',
  'intermediate',
  false,
  'warm-up.png',
  'Perform the movement with controlled tempo and proper form.'
),
(
  'Wide Pull Up',
  'wide-pull-up',
  'back',
  '{}',
  'bodyweight',
  'other',
  'strength',
  'intermediate',
  false,
  'wide-pull-up.png',
  'Perform the movement with controlled tempo and proper form.'
),
(
  'Wide-Elbow Triceps Press (Dumbbell)',
  'wide-elbow-triceps-press-dumbbell',
  'triceps',
  '{}',
  'dumbbell',
  'push',
  'strength',
  'intermediate',
  false,
  'wide-elbow-triceps-press-dumbbell.png',
  'Perform the movement with controlled tempo and proper form.'
),
(
  'Wrist Roller',
  'wrist-roller',
  'full_body',
  '{}',
  'bodyweight',
  'other',
  'strength',
  'intermediate',
  false,
  'wrist-roller.png',
  'Perform the movement with controlled tempo and proper form.'
),
(
  'Yoga',
  'yoga',
  'full_body',
  '{}',
  'bodyweight',
  'other',
  'strength',
  'intermediate',
  false,
  'yoga.png',
  'Perform the movement with controlled tempo and proper form.'
),
(
  'Zercher Squat',
  'zercher-squat',
  'quadriceps',
  '{}',
  'bodyweight',
  'squat',
  'strength',
  'intermediate',
  false,
  'zercher-squat.png',
  'Perform the movement with controlled tempo and proper form.'
),
(
  'Zottman Curl (Dumbbell)',
  'zottman-curl-dumbbell',
  'biceps',
  '{}',
  'dumbbell',
  'isolation',
  'strength',
  'intermediate',
  false,
  'zottman-curl-dumbbell.png',
  'Perform the movement with controlled tempo and proper form.'
)
ON CONFLICT (name) DO NOTHING;
